export const labels = {
  appName: 'SismovBE',

  screenTitles: {
    dashboard: 'Dashboard',
    settings: 'Configurações',
    home: 'SismovBE',
    movements: 'Movimentações',
    requests: 'Solicitações',
    pendingAsiweb: 'Pendências ASIWEB',
    assets: 'Bens',
    units: 'Unidades',
    users: 'Usuários',
    login: 'Entrar',
    forgotPassword: 'Recuperar senha',
  },

  nav: {
    resumo: 'Resumo',
    movements: 'Movimentações',
    requests: 'Solicitações',
    pendingAsiweb: 'Pendências ASIWEB',
    assets: 'Bens',
    units: 'Unidades',
    users: 'Usuários',
    settings: 'Configurações',
  },

  resumo: {
    pendingAsiweb: 'Pendências ASIWEB',
    newRequests: 'Solicitações novas',
    movementsToday: 'Movimentações hoje',
    avgProcessTime: 'Tempo médio p/ processar',
    pendingAsiwebTop6: 'Pendências ASIWEB (Top 6)',
    recentActivity: 'Atividade recente',
    noData: 'Nenhum dado',
    hours: 'horas',
  },

  status: {
    active: 'Ativo',
    inactive: 'Inativo',
    pending: 'Pendente',
    cancelled: 'Cancelado',
    completed: 'Concluído',
    requested: 'Solicitado',
    picked_up: 'Retirado',
    received: 'Recebido',
    delivered: 'Entregue',
    canceled: 'Cancelado',
  },

  buttons: {
    save: 'Salvar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Excluir',
    back: 'Voltar',
    next: 'Próximo',
    goToSettings: 'Ir para Configurações',
  },

  messages: {
    welcomeDashboard: 'Bem-vindo ao SismovBE',
    dashboardUnderConstruction: 'Dashboard em construção. Use a navegação lateral para explorar.',
    settingsUnderConstruction: 'Página de configurações em construção.',
    appUnderConstruction: 'App mobile em construção. Use os botões abaixo para navegar.',
    permissionDenied: 'Você não tem permissão para acessar esta página.',
    permissionDeniedHint: 'Entre em contato com o administrador para solicitar acesso.',
    noProfile: 'Perfil não encontrado. Entre em contato com o administrador.',
    profileInactive: 'Seu perfil está inativo. Entre em contato com o administrador.',
    checkEmailForReset: 'Verifique seu e-mail para redefinir a senha.',
    loginError: 'E-mail ou senha inválidos.',
  },

  auth: {
    email: 'E-mail',
    password: 'Senha',
    login: 'Entrar',
    logout: 'Sair',
    forgotPassword: 'Esqueci minha senha',
    sendResetLink: 'Enviar link de redefinição',
    backToLogin: 'Voltar ao login',
  },

  users: {
    createUser: 'Novo usuário',
    editUser: 'Editar usuário',
    fullName: 'Nome completo',
    role: 'Perfil',
    unit: 'Unidade',
    selectRole: 'Selecione o perfil',
    selectUnit: 'Selecione uma unidade',
    noUnit: 'Sem unidade',
    noUsers: 'Nenhum usuário encontrado.',
    userFallback: 'Usuário',
    resetPassword: 'Resetar senha',
    activate: 'Ativar',
    deactivate: 'Desativar',
    roleRequired: 'Perfil é obrigatório',
    emailRequired: 'E-mail é obrigatório',
    fullNameRequired: 'Nome é obrigatório',
    unitRequiredForUnitUser: 'Unidade é obrigatória para perfil Unidade',
    unitRequired: 'Unidade é obrigatória para todos os usuários',
    creating: 'Criando...',
    createSuccess: 'Usuário criado. Link de redefinição de senha enviado por e-mail.',
    resetSuccess: 'E-mail de redefinição de senha enviado.',
    updateSuccess: 'Usuário atualizado.',
    activateSuccess: 'Usuário ativado.',
    deactivateSuccess: 'Usuário desativado.',
    createError: 'Erro ao criar usuário.',
    resetError: 'Erro ao enviar e-mail de redefinição.',
  },

  roles: {
    PATRIMONIO_ADMIN: 'Patrimônio Admin',
    SEAME_ADMIN: 'SEAME Admin',
    TECH: 'Técnico',
    UNIT_USER: 'Unidade',
  },

  units: {
    createUnit: 'Nova unidade',
    editUnit: 'Editar unidade',
    ulCode: 'Código UL',
    ulCodePlaceholder: '000000',
    ulCodeRequired: 'Código UL deve ter 6 dígitos',
    name: 'Nome',
    nameRequired: 'Nome é obrigatório',
    active: 'Ativo',
    createSuccess: 'Unidade criada.',
    updateSuccess: 'Unidade atualizada.',
    activateSuccess: 'Unidade ativada.',
    deactivateSuccess: 'Unidade desativada.',
    createError: 'Erro ao criar unidade.',
    updateError: 'Erro ao atualizar unidade.',
    ulCodeExists: 'Código UL já existe.',
  },

  responsibles: {
    title: 'Responsáveis',
    add: 'Adicionar responsável',
    edit: 'Editar responsável',
    name: 'Nome',
    email: 'E-mail',
    primary: 'Principal',
    setPrimary: 'Definir como principal',
    createSuccess: 'Responsável adicionado.',
    updateSuccess: 'Responsável atualizado.',
    deleteSuccess: 'Responsável removido.',
    nameRequired: 'Nome é obrigatório.',
    emailRequired: 'E-mail é obrigatório.',
  },

  assets: {
    createAsset: 'Novo bem',
    editAsset: 'Editar bem',
    tombamento: 'Tombamento',
    tombamentoRequired: 'Tombamento é obrigatório',
    tombamentoExists: 'Tombamento já existe.',
    description: 'Descrição',
    descriptionRequired: 'Descrição é obrigatória',
    barcode: 'Código de barras',
    unit: 'Unidade',
    unitRequired: 'Unidade é obrigatória',
    active: 'Ativo',
    createSuccess: 'Bem cadastrado.',
    updateSuccess: 'Bem atualizado.',
    activateSuccess: 'Bem ativado.',
    deactivateSuccess: 'Bem desativado.',
  },

  importCsv: {
    title: 'Importar CSV',
    selectFile: 'Selecionar arquivo',
    preview: 'Pré-visualização',
    rowsOk: 'Linhas OK',
    rowsError: 'Linhas com erro',
    import: 'Importar',
    importing: 'Importando...',
    done: 'Concluído',
    report: 'Relatório',
    imported: 'Importados/atualizados',
    failed: 'Falharam',
    noRows: 'Nenhuma linha para importar',
    invalidFormat: 'Formato inválido. Use: tombamento,description,ul_code_atual,barcode_value',
    ulCodeNotFound: 'UL não encontrada',
    ulEmpty: 'UL vazia',
    tombamentoEmpty: 'Tombamento vazio',
    tombamentoInvalid: 'Tombamento inválido',
    descriptionEmpty: 'Descrição vazia',
    tombamentoDuplicate: 'Tombamento duplicado no CSV',
    fillBarcodeWithTombamento: 'Preencher código de barras com tombamento quando vazio',
    validating: 'Validando...',
    back: 'Voltar',
    ulOriginal: 'UL original',
    ulNormalized: 'UL normalizada',
    tombamentoOriginal: 'Tomb. original',
    tombamentoNormalized: 'Tomb. normalizado',
  },

  requests: {
    title: 'Solicitações',
    filters: 'Filtros',
    filterApply: 'Filtrar',
    originUnit: 'Unidade origem',
    requestedBy: 'Solicitante',
    date: 'Data',
    viewDetail: 'Ver detalhe',
    viewHistory: 'Ver histórico',
    items: 'Itens',
    noItems: 'Nenhum item',
    history: 'Histórico',
  },

  movements: {
    title: 'Movimentações',
    filters: 'Filtros',
    status: 'Status',
    origin: 'Origem',
    destination: 'Destino',
    pickupTech: 'Técnico retirada',
    period: 'Período',
    from: 'De',
    to: 'Até',
    pickupAt: 'Retirado em',
    receivedAt: 'Recebido em',
    deliveredAt: 'Entregue em',
    timeline: 'Timeline',
    notes: 'Observações',
    asiweb: 'ASIWEB',
    asiwebPending: 'Pendente',
    asiwebProcessed: 'Processado',
    asiwebStatus: 'ASIWEB',
    processedAt: 'Processado em',
    processedBy: 'Processado por',
    asiwebYes: 'Sim',
    asiwebNo: 'Não',
  },

  pendingAsiweb: {
    title: 'Pendências ASIWEB',
    tabPending: 'Pendentes',
    tabProcessed: 'Processadas',
    tabProcessedDesc: 'Histórico de movimentações já processadas no ASIWEB (auditoria)',
    markProcessed: 'Marcar processado',
    exportCsv: 'Exportar CSV',
    noPending: 'Nenhuma pendência',
    noProcessed: 'Nenhuma processada',
    processedSuccess: 'Marcado como processado.',
    processedAt: 'Processado em',
    processedBy: 'Processado por',
  },

  tabs: {
    queue: 'Chamados',
    move: 'Movimentação',
    receive: 'Recebimento',
    profile: 'Perfil',
    request: 'Solicitar',
    myRequests: 'Minhas',
  },

  tech: {
    queue: 'Fila',
    receive: 'Receber',
    move: 'Movimentar',
    origin: 'Origem',
    destination: 'Destino',
    startPickup: 'Iniciar recolhimento (Pickup)',
    finalizePickup: 'Finalizar recolhimento (Pickup)',
    goToReceive: 'Ir para Receber',
    confirmReceive: 'Confirmar recebimento no destino (SEAME Bens Recebidos)',
    confirmReceiveAt: 'Confirmar recebimento em',
    pickupConfirm: 'Confirmar que você está iniciando o recolhimento destes itens?',
    receiveConfirm: 'Confirmar que os bens foram recebidos no destino SEAME?',
    selectUnit: 'Selecionar unidade',
    moveSuccess: 'Movimentação criada. Confirme o recebimento na aba Receber.',
    selectOriginDest: 'Selecione origem e destino',
    selectOriginDestHint: 'Para adicionar bens ao lote, selecione a unidade de origem e a unidade de destino.',
    selectOriginDestBeforeInput: 'Selecione a Origem e o Destino do(s) bem(ns) antes de informar o tombamento.',
    selectOriginDestToEnable: 'Selecione origem e destino para habilitar',
    duplicateInLot: 'Este tombamento já está no lote.',
    addedToLot: 'Bem {tombamento} adicionado ao lote',
    invalidTombamentoFormat: 'Tombamento inválido (formato inesperado).',
    receiveSuccess: 'Bem(ns) recebido(s). Em breve será feito o ajuste no sistema ASIWEB',
    tombamentoNotInReceive: 'Este bem não pertence a este recebimento.',
    confirmReceiveButton: 'Confirmar recebimento',
    receiveNoItems: 'Não há itens nesta movimentação. Não é possível confirmar.',
    noLabelSection: 'Sem etiqueta?',
    labelMissingCheckbox: 'Etiqueta ausente/danificada',
    labelMissingHint: 'Use esta opção somente se não for possível ler a etiqueta.',
    validateTombamento: 'Validar',
    receiveButton: 'Receber',
    informTombamento: 'Informe o tombamento.',
  },

  unitUser: {
    requestShipment: 'Solicitar envio',
    myRequests: 'Minhas solicitações',
    scanBarcode: 'Escanear código',
    manualEntry: 'Inserir manualmente',
    tombamento: 'Tombamento',
    addItem: 'Adicionar item',
    cart: 'Lote de bens',
    finishRequest: 'Finalizar solicitação',
    noItems: 'Nenhum bem no lote',
    addedToLot: 'Bem {tombamento} adicionado ao lote',
    cartEmpty: 'Lote vazio',
    assetFound: 'Bem encontrado',
    assetNotFound: 'Bem não encontrado',
    takePhoto: 'Tirar foto do bem/etiqueta',
    cancel: 'Cancelar solicitação',
    cancelConfirm: 'Cancelar esta solicitação? Só é possível cancelar enquanto estiver pendente.',
  },

  settings: {
    title: 'Configurações',
    seameGroupEmail: 'E-mail do grupo SEAME',
    seameReceiptsUlCode: 'UL de recibos SEAME',
    seameGroupEmailRequired: 'E-mail do grupo é obrigatório.',
    ulCodeRequired: 'Selecione uma unidade.',
    ulCodeNotFound: 'Unidade não encontrada.',
    updateSuccess: 'Configurações salvas.',
    onlyPatrimonioAdmin: 'Apenas Patrimônio Admin pode editar configurações.',
  },
} as const;
